parameters:
#    flow_frontend.example.class: Flow\FrontendBundle\Example

services:
#    flow_frontend.example:
#        class: %flow_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
